services:
  web:
    build: ..
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: your_mysql_root_password
      MYSQL_DB: mathbuddy
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: mathbuddy
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: